[build]
  publish = "."
  base = "."

[[redirects]]
  from = "/"
  to = "/views/login.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/views/login.html"
  status = 200

# Para archivos estáticos (CSS, JS, imágenes)
[[redirects]]
  from = "/css/*"
  to = "/public/css/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/public/js/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/public/images/:splat"
  status = 200