[build]
  publish = "."
  base = "."

[[redirects]]
  from = "/"
  to = "/views/login.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/views/login.html"
  status = 200

# Redirecciones CORRECTAS para archivos estáticos
[[redirects]]
  from = "/css/*"
  to = "/public/css/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/public/js/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/public/images/:splat"
  status = 200

[[redirects]]
  from = "/img/*"
  to = "/public/img/:splat"
  status = 200

# IMPORTANTE: Agregar esto para que Netlify sirva los archivos estáticos directamente
[[headers]]
  for = "/public/*"
  [headers.values]
    "Access-Control-Allow-Origin" = "*"