[build]
  publish = "."
  base = "."

# Redirigir todas las rutas a login.html EXCEPTO los archivos estáticos
[[redirects]]
  from = "/*"
  to = "/views/login.html"
  status = 200
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

# Servir archivos estáticos directamente
[[redirects]]
  from = "/css/*"
  to = "/public/css/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/public/js/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/public/images/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/public/assets/:splat"
  status = 200