[build]
  publish = "public"
  base = "/"

# Opcional: Si quieres que login.html sea la página principal
[[redirects]]
  from = "/"
  to = "/login.html"
  status = 200

# Opcional: Si tienes un SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 200